print("My daily routine as follows")
print("1# I wake up and brush my teeth around 6 am.")
print("2# I eat breakfast at my dinner table 6:05 am.")
print("3# I check my backpack for if I have anything around 7:00 AM.")
print("4# I go to school at 8:15 AM.")
print("5# I come back home and watch TV at 3:40 PM.")
print("6# I start to do my work at 5:00 PM.")
print("7# I go to Taekwondo or other sports at 7:30 PM")
print("8# I finish my homework and go to bed at 10:30 PM.")